import { execFile, exec } from 'child_process'
import { promisify } from 'util'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { parseVTT } from './vtt'
import { parseSRT } from './srt'
import type { SubtitleEntry } from './srt'

const execFileAsync = promisify(execFile)
const execAsync = promisify(exec)

export interface YouTubeSubtitleInfo {
  langCode: string
  langName: string
  isAutoGenerated: boolean
}

export interface YouTubeVideoInfo {
  id: string
  title: string
  channel: string
  duration: number
  subtitles: YouTubeSubtitleInfo[]
}

// Find yt-dlp binary
async function findYtDlp(): Promise<string | null> {
  const possiblePaths = [
    'yt-dlp', // In PATH
    '/usr/local/bin/yt-dlp',
    '/opt/homebrew/bin/yt-dlp',
    path.join(os.homedir(), '.local/bin/yt-dlp'),
  ]

  for (const ytdlpPath of possiblePaths) {
    try {
      await execFileAsync(ytdlpPath, ['--version'])
      return ytdlpPath
    } catch {
      // Try next path
    }
  }

  return null
}

export async function checkYtDlpAvailable(): Promise<boolean> {
  const ytdlp = await findYtDlp()
  return ytdlp !== null
}

export async function getYouTubeVideoInfo(url: string): Promise<YouTubeVideoInfo> {
  const ytdlp = await findYtDlp()
  if (!ytdlp) {
    throw new Error('yt-dlp not found. Please install: brew install yt-dlp')
  }

  // Validate YouTube URL
  if (!isValidYouTubeUrl(url)) {
    throw new Error('Invalid YouTube URL')
  }

  try {
    const { stdout } = await execFileAsync(ytdlp, [
      '--dump-json',
      '--no-download',
      '--no-warnings',
      url,
    ], { timeout: 30000 })

    const info = JSON.parse(stdout)

    // Parse available subtitles
    const subtitles: YouTubeSubtitleInfo[] = []

    // Manual subtitles
    if (info.subtitles) {
      for (const [langCode, formats] of Object.entries(info.subtitles)) {
        if (Array.isArray(formats) && formats.length > 0) {
          subtitles.push({
            langCode,
            langName: getLangName(langCode),
            isAutoGenerated: false,
          })
        }
      }
    }

    // Auto-generated subtitles
    if (info.automatic_captions) {
      for (const [langCode, formats] of Object.entries(info.automatic_captions)) {
        if (Array.isArray(formats) && formats.length > 0) {
          // Only add if not already in manual subtitles
          if (!subtitles.some(s => s.langCode === langCode)) {
            subtitles.push({
              langCode,
              langName: getLangName(langCode),
              isAutoGenerated: true,
            })
          }
        }
      }
    }

    return {
      id: info.id,
      title: info.title || 'YouTube Video',
      channel: info.channel || info.uploader || 'Unknown',
      duration: info.duration || 0,
      subtitles,
    }
  } catch (error) {
    if (error instanceof Error && error.message.includes('timeout')) {
      throw new Error('Request timed out. Please try again.')
    }
    throw new Error(`Failed to get video info: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

export async function downloadYouTubeSubtitle(
  url: string,
  langCode: string,
  preferAutoGenerated: boolean = false,
): Promise<{ title: string; entries: SubtitleEntry[] }> {
  const ytdlp = await findYtDlp()
  if (!ytdlp) {
    throw new Error('yt-dlp not found. Please install: brew install yt-dlp')
  }

  // Create temp directory
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'lexis-youtube-'))

  try {
    // Download subtitle
    const args = [
      '--write-sub',
      '--write-auto-sub',
      '--sub-lang', langCode,
      '--sub-format', 'vtt/srt/best',
      '--skip-download',
      '--no-warnings',
      '-o', path.join(tempDir, '%(title)s.%(ext)s'),
      url,
    ]

    await execFileAsync(ytdlp, args, { timeout: 60000 })

    // Find the downloaded subtitle file
    const files = fs.readdirSync(tempDir)
    const subFile = files.find(f => f.endsWith('.vtt') || f.endsWith('.srt'))

    if (!subFile) {
      throw new Error(`No subtitle found for language: ${langCode}`)
    }

    const subPath = path.join(tempDir, subFile)
    const content = fs.readFileSync(subPath, 'utf-8')

    // Parse subtitle
    const entries = subFile.endsWith('.vtt') ? parseVTT(content) : parseSRT(content)

    if (entries.length === 0) {
      throw new Error('No subtitle entries found in the downloaded file')
    }

    // Extract title from filename (remove extension and lang code)
    let title = subFile
      .replace(/\.[^.]+$/, '') // Remove extension
      .replace(/\.[a-z]{2}(-[A-Z]{2})?$/, '') // Remove lang code like .en or .en-US

    // Get video info for better title
    try {
      const info = await getYouTubeVideoInfo(url)
      title = info.title
    } catch {
      // Use filename-derived title
    }

    return { title, entries }
  } finally {
    // Cleanup temp directory
    try {
      fs.rmSync(tempDir, { recursive: true })
    } catch {
      // Ignore cleanup errors
    }
  }
}

function isValidYouTubeUrl(url: string): boolean {
  const patterns = [
    /^https?:\/\/(www\.)?youtube\.com\/watch\?v=[\w-]+/,
    /^https?:\/\/youtu\.be\/[\w-]+/,
    /^https?:\/\/(www\.)?youtube\.com\/shorts\/[\w-]+/,
    /^https?:\/\/(www\.)?youtube\.com\/embed\/[\w-]+/,
  ]
  return patterns.some(p => p.test(url))
}

function getLangName(code: string): string {
  const names: Record<string, string> = {
    en: 'English',
    'en-US': 'English (US)',
    'en-GB': 'English (UK)',
    ja: 'Japanese',
    zh: 'Chinese',
    'zh-Hans': 'Chinese (Simplified)',
    'zh-Hant': 'Chinese (Traditional)',
    ko: 'Korean',
    vi: 'Vietnamese',
    fr: 'French',
    es: 'Spanish',
    de: 'German',
    pt: 'Portuguese',
    ru: 'Russian',
    it: 'Italian',
    ar: 'Arabic',
    hi: 'Hindi',
    th: 'Thai',
    id: 'Indonesian',
  }
  return names[code] || code
}
